version: 2
updates:
  - package-ecosystem: pip
    directory: /
    ignore:
      - dependency-name: Django
        versions:
          - '>=3.3'
      - dependency-name: kubernetes
        versions:
          - '>=28'
    groups:
      minor-updates:
        update-types: [minor, patch]
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: '-'

  - package-ecosystem: npm
    directory: /
    groups:
      minor-updates:
        update-types: [minor, patch]
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /mtp_common/templates/mtp_common/build_tasks
    groups:
      minor-updates:
        update-types: [minor, patch]
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: '-'
