version: 2
updates:
  - package-ecosystem: pip
    directory: /
    ignore:
      - dependency-name: Django
        versions:
          - ">=2.3"
      - dependency-name: kubernetes
        versions:
          - ">=24"
    schedule:
      interval: monthly
    pull-request-branch-name:
      separator: '-'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: npm
    directory: /mtp_common/templates/mtp_common/build_tasks
    schedule:
      interval: monthly
