version: 2
updates:
  - package-ecosystem: pip
    directory: /
    ignore:
      - dependency-name: Django
        update-types:
          - version-update:semver-major
      - dependency-name: kubernetes
        update-types:
          - version-update:semver-major
    schedule:
      interval: weekly
    pull-request-branch-name:
      separator: '-'
