language: python
python:
  - 3.5
before_install:
  - pip install -U setuptools pip wheel
install:
  - pip install .
  - python run.py python_dependencies --extras testing
script:
  - python run.py --verbosity 2 test
