version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10-node
    working_directory: /tmp/mtp
    steps:
      - checkout
      - run:
          name: Install os dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y gettext
#      - restore_cache:
#          keys:
#            - py-v1-{{ checksum "setup.py" }}
#            - py-v1-
      - run:
          name: Install python dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -U setuptools pip wheel
            pip install --editable .[testing]
            python --version && pip --version
      - save_cache:
          key: py-v1-{{ checksum "setup.py" }}
          paths:
            - ./venv
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python run.py --verbosity 2 test

workflows:
  version: 2
  test:
    jobs:
      - test
